#!/usr/bin/env bash
# Heterogeneity RATIO SWEEP (structural ablation, experiment 1).
# Design: docs/superpowers/specs/2026-07-23-edpp-structural-ablations-design.md
#
# THE QUESTION the paper currently answers at ONE ratio (the crippled-A100 cell,
# decode-theta ratio ~4.8x, tab:grid row "heterogeneous"): at what heterogeneity
# ratio do the TTFT-currency rules (least-TTFT, Kairos) break, and where does
# drift-plus-VaR's margin over them peak? This turns the single heterogeneous
# cell into the curve that defends the paper's one uncontested claim -- that
# hardware heterogeneity is the regime none of the published rules address.
#
# KNOB (uniform Nx slowdown): the slow decode node is generated by scaling BOTH
# tflops_peak and bw_peak_tbs by 1/N via scripts/calibration/repro_theta_by_gpu.sh.
# For this decode-bound workload the fitted decode per-token coefficient c1 comes
# out at ratio EXACTLY N (memory-bound), so the measured decode-theta ratio equals
# the nominal knob. N=1 is the homogeneous sanity point (congestion spread -> 0,
# dpVaR should tie the least-TTFT family). N~5 reproduces the published cell.
#
# TOPOLOGY: 1P2D (one dedicated prefill + one fast + one slow decode), matching
# the validated tab:grid heterogeneous regime EXACTLY (--prefill-instances 1
# --decode-instances 2, TP=4 so the 8-GPU fast pool absorbs instance_0 (prefill)
# and instance_1 (fast decode), overflowing instance_2 (slow decode) to the
# 4-GPU slow pool).
#
# METRIC: goodput per arm per N (primary), and regret-vs-per-N-optimum-oracle
# (headline signal -- normalizes out the everyone-wins / everyone-loses bands so
# policy separation is visible). The oracle is a per-N grid search over the
# fixed fast/slow decode split (searched on seed 42, evaluated over all seeds).
# The operator SLO is HELD FIXED across N (batch: ttft 60s, e2e 8s, itl 500ms) --
# the oracle re-optimizes per N so regret is comparable across the curve.
#
# Output length is VARIABLE (lognormal, CV~0.42) to match sec:eval:setup.
#
# Usage (from repo root):
#   bash campaigns/edpp-study/repro_hetero_ratio_sweep.sh
#   RATE=10 CAPN=8 SEEDS="42 7 123" RATIOS="1.0 1.2 1.5 2.0 3.0 5.0" \
#     bash campaigns/edpp-study/repro_hetero_ratio_sweep.sh
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

MODEL="${MODEL:-meta-llama/llama-3.3-70b-instruct}"
COEF="${COEFFS:-scripts/calibration/coeffs-llama70b-h100-tp4.json}"   # fast = H100 base + fallback
D=campaigns/edpp-study/specs/hetero_ratio
OUT="${OUT:-campaigns/edpp-study/out/hetero_ratio}"
SEEDS="${SEEDS:-42 7 123}"
RATE="${RATE:-10}"; CAPN="${CAPN:-8}"
RATIOS="${RATIOS:-1.0 1.2 1.5 2.0 3.0 5.0}"
VAROUT="${VAROUT:-0.4}"                 # output-length lognormal sigma (CV~0.42)
KBETAS="${KBETAS:-0.25 0.5 1.0}"        # Kairos safety margin, best-per-seed (tuned in its favor)
mkdir -p "$D" "$OUT"
[[ -x ./blis ]] || go build -o blis main.go

# tag for ratio N (e.g. 2.0 -> ratio2p0), matching the coeff-ladder filenames.
tag(){ printf 'ratio%s' "$(echo "$1" | tr '.' 'p')"; }
# ensure the slow-node coeffs for ratio N exist; generate via uniform Nx if not.
ensure_coeffs(){ local N="$1" t; t="$(tag "$N")"
  local f="scripts/calibration/coeffs-llama70b-$t-tp4.json"
  if [[ ! -f "$f" ]]; then
    local TF BW; TF=$(python3 -c "print(f'{1979.0/$N:.4f}')"); BW=$(python3 -c "print(f'{3.35/$N:.5f}')")
    echo "  generating $f (uniform ${N}x: tflops=$TF bw=$BW)" >&2
    bash scripts/calibration/repro_theta_by_gpu.sh "$t" "$TF" "$BW" A100 "/tmp/theta_$t" >/dev/null 2>&1
  fi
  echo "$f"
}

# per-ratio heterogeneous bundle: H100 fast pool (2 tp4 slots) + A100 slow pool (1 slot).
# hw_config_by_gpu pins the DES roofline; coeffs_by_gpu supplies each instance's theta_i.
write_bundle(){ local N="$1" slowcoef="$2"
  local TF BW; TF=$(python3 -c "print(f'{1979.0/$N:.4f}')"); BW=$(python3 -c "print(f'{3.35/$N:.5f}')")
  cat > "$D/bundle_$(tag "$N").yaml" <<YAML
node_pools:
  - {name: fast, gpu_type: H100, gpus_per_node: 8, gpu_memory_gib: 80.0, initial_nodes: 1, min_nodes: 1, max_nodes: 1, cost_per_hour: 0.0, provisioning_delay: {mean: 0.0, stddev: 0.0}}
  - {name: slow, gpu_type: A100, gpus_per_node: 4, gpu_memory_gib: 80.0, initial_nodes: 1, min_nodes: 1, max_nodes: 1, cost_per_hour: 0.0, provisioning_delay: {mean: 0.0, stddev: 0.0}}
hw_config_by_gpu:
  H100: {tflops_peak: 1979.0, bw_peak_tbs: 3.35, mfu_prefill: 0.5, mfu_decode: 0.5}
  A100: {tflops_peak: $TF, bw_peak_tbs: $BW, mfu_prefill: 0.5, mfu_decode: 0.5}
coeffs_by_gpu:
  H100: $COEF
  A100: $slowcoef
YAML
  echo "$D/bundle_$(tag "$N").yaml"
}

# saturating decode-bound workload, variable output (lognormal, mean 64).
outdist(){ local mu mx; mu=$(python3 -c "import math;print('%.4f'%(math.log($1)-$VAROUT*$VAROUT/2))")
  mx=$(python3 -c "print(int($1*8)+16)")
  echo "{type: lognormal, params: {mu: $mu, sigma: $VAROUT, min: 4, max: $mx}}"; }
write_workload(){ local seed="$1"
  cat > "$D/w.yaml" <<YAML
version: "2"
seed: $seed
category: language
aggregate_rate: $RATE
num_requests: 400
clients:
  - {id: hw, tenant_id: batch-jobs, slo_class: batch, rate_fraction: 1.0, streaming: false, arrival: {process: poisson}, input_distribution: {type: constant, params: {value: 256}}, output_distribution: $(outdist 64), prefix_group: hw, prefix_length: 0}
YAML
}

gp(){ python3 -c "import json;print('%.4f'%json.load(open('$1'))['per_class']['batch']['slo_attainment'])" 2>/dev/null||echo NA; }
XSLO=(--slo-ttft batch=60s --slo-e2e batch=8s --slo-itl batch=500ms)
EC=(--edpp-coeffs "$COEF" --edpp-tadm-estimator rollforward --edpp-c-xfer-size-aware)

# run one arm; $1=tag $2=bundle $3=seed rest=policy flags; echoes goodput.
run(){ local tg="$1" bundle="$2" seed="$3"; shift 3
  ./blis run --model "$MODEL" --workload-spec "$D/w.yaml" \
    --num-instances 3 --prefill-instances 1 --decode-instances 2 --policy-config "$bundle" \
    --max-num-running-reqs "$CAPN" "${XSLO[@]}" --seed "$seed" "$@" \
    --metrics-path "$OUT/$tg.json" >/dev/null 2>&1 || true
  gp "$OUT/$tg.json"; }

# fixed-plan oracle: first FRAC% of every 100 requests -> instance_1 (fast), rest -> instance_2 (slow).
write_plan(){ local frac="$1"
  python3 -c "
import csv
w=csv.DictWriter(open('$OUT/plan.csv','w',newline=''),fieldnames=['request_id','decode_instance','prefill_instance']);w.writeheader()
for i in range(400): w.writerow({'request_id':f'request_{i}','decode_instance':('instance_1' if i%100<$frac else 'instance_2'),'prefill_instance':'instance_0'})"
}
oracle_run(){ local tg="$1" bundle="$2" seed="$3"
  ./blis run --model "$MODEL" --workload-spec "$D/w.yaml" \
    --num-instances 3 --prefill-instances 1 --decode-instances 2 --policy-config "$bundle" \
    --max-num-running-reqs "$CAPN" "${XSLO[@]}" --seed "$seed" --pd-plan "$OUT/plan.csv" \
    --metrics-path "$OUT/$tg.json" >/dev/null 2>&1 || true
  gp "$OUT/$tg.json"; }

CSV="$OUT/ratio_sweep.csv"; echo "ratio,arm,seed,goodput" > "$CSV"
emit(){ echo "$1,$2,$3,$4" >> "$CSV"; }
echo "HETERO RATIO SWEEP  1P2D  rate=$RATE cap=$CAPN  seeds=[$SEEDS]  ratios=[$RATIOS]  out-CV~0.42" >&2
printf "%-5s| %-8s %-8s %-8s %-8s %-8s %-8s | %-8s\n" "N" "always" "prefix" "kairos*" "leastT" "dpp" "dpVaR" "optimum" >&2

for N in $RATIOS; do
  SLOWC="$(ensure_coeffs "$N")"
  BUNDLE="$(write_bundle "$N" "$SLOWC")"
  declare -a A=() P=() K=() L=() DP=() VV=() O=()

  # --- per-N optimum split: grid-search fast-fraction on seed 42, then eval over all seeds ---
  write_workload 42
  best_frac=0; best_gp=-1
  for frac in 0 10 20 30 40 50 60 70 80 90 100; do
    write_plan "$frac"; g=$(oracle_run "o_${N}_${frac}" "$BUNDLE" 42)
    awk "BEGIN{exit !($g > $best_gp)}" 2>/dev/null && { best_gp=$g; best_frac=$frac; }
  done
  write_plan "$best_frac"

  for s in $SEEDS; do
    write_workload "$s"
    a=$(run "a_${N}_$s" "$BUNDLE" "$s" --pd-decider always);                                                        A+=("$a");  emit "$N" always "$s" "$a"
    p=$(run "p_${N}_$s" "$BUNDLE" "$s" --pd-decider prefix-threshold --pd-prefix-threshold 16);                      P+=("$p");  emit "$N" prefix "$s" "$p"
    kb=(); for bb in $KBETAS; do kb+=("$(run "k_${N}_${s}_$bb" "$BUNDLE" "$s" --pd-decider edpp "${EC[@]}" --edpp-tau-ttft 60s --edpp-tau-itl 500ms --edpp-rule kairos --kairos-beta "$bb")"); done
    k=$(printf '%s\n' "${kb[@]}" | sort -g | tail -1);                                                              K+=("$k");  emit "$N" kairos "$s" "$k"
    l=$(run "l_${N}_$s" "$BUNDLE" "$s" --pd-decider edpp "${EC[@]}" --edpp-tau-ttft 60s --edpp-tau-itl 500ms --edpp-rule least-ttft); L+=("$l"); emit "$N" least-ttft "$s" "$l"
    dp=$(run "dp_${N}_$s" "$BUNDLE" "$s" --pd-decider edpp "${EC[@]}" --edpp-tau-ttft 60s --edpp-tau-itl 500ms --edpp-joint);          DP+=("$dp"); emit "$N" dpp "$s" "$dp"
    vv=$(run "vv_${N}_$s" "$BUNDLE" "$s" --pd-decider edpp "${EC[@]}" --edpp-tau-ttft 60s --edpp-tau-itl 500ms --edpp-tau-e2e 8s --edpp-rule var --edpp-var-metric util --edpp-joint --edpp-var-congestion --edpp-var-normalize --edpp-var-congestion-weight 1 --edpp-var-deployable); VV+=("$vv"); emit "$N" dpVaR "$s" "$vv"
    o=$(oracle_run "oe_${N}_$s" "$BUNDLE" "$s");                                                                     O+=("$o");  emit "$N" optimum "$s" "$o"
  done
  m(){ python3 -c "import sys;xs=[float(x) for x in sys.argv[1:] if x not in ('NA','')];print('%.3f'%(sum(xs)/len(xs)) if xs else 'NA')" "$@"; }
  printf "%-5s| %-8s %-8s %-8s %-8s %-8s %-8s | %-8s (opt split=%s%% fast)\n" \
    "$N" "$(m "${A[@]}")" "$(m "${P[@]}")" "$(m "${K[@]}")" "$(m "${L[@]}")" "$(m "${DP[@]}")" "$(m "${VV[@]}")" "$(m "${O[@]}")" "$best_frac" >&2
done
echo "done -> $CSV" >&2